<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DIAMOND-QA51L" name="Personal Loan" tests="5" failures="1" timestamp="13 Sep 2022 18:07:09 GMT" time="0.102" errors="0">
  <testcase name="demo" time="0.011" classname="testNGTutorial.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testNGTutorial.day1.demo(day1.java:11)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase name="demo2" time="0.001" classname="testNGTutorial.day1"/>
  <testcase name="ploan2" time="0.015" classname="testNGTutorial.day2"/>
  <testcase name="ploan3" time="0.009" classname="testNGTutorial.day2"/>
  <testcase name="APILoginHomeLoan" time="0.002" classname="testNGTutorial.day4"/>
</testsuite> <!-- Personal Loan -->
